using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using Unity.CompilationPipeline.Common.ILPostProcessing;

namespace Tutorial.CodeGen
{
    /// <summary>
    /// One tutorial method binding read from the generated instrumentation manifest
    /// </summary>
    internal sealed class TutorialInstrumentationBinding
    {
        #region Properties

        public string GraphGuid { get; }
        public string ScriptName { get; }
        public string MethodName { get; }
        public string StepGuid { get; }

        #endregion

        #region Constructor

        public TutorialInstrumentationBinding(string graphGuid, string scriptName, string methodName, string stepGuid)
        {
            GraphGuid = graphGuid;
            ScriptName = scriptName;
            MethodName = methodName;
            StepGuid = stepGuid;
        }

        #endregion
    }

    /// <summary>
    /// Read the instrumentation manifest generated by the Tutorial Tool
    /// </summary>
    internal static class TutorialInstrumentationManifestReader
    {
        #region Constants

        private const string ManifestRelativePath = "ProjectSettings/Tutorial/TutorialInstrumentationManifest.json";

        #endregion

        #region Public Methods

        /// <summary>
        /// Read every tutorial method binding stored inside the generated manifest
        /// </summary>
        public static bool TryRead(ICompiledAssembly compiledAssembly, out List<TutorialInstrumentationBinding> bindings, out string failureReason)
        {
            bindings = new List<TutorialInstrumentationBinding>();
            failureReason = string.Empty;

            if (!TryFindManifestPath(compiledAssembly, out string manifestPath))
            {
                return true;
            }

            try
            {
                string json = File.ReadAllText(manifestPath);

                if (string.IsNullOrWhiteSpace(json))
                {
                    failureReason = $"Tutorial instrumentation manifest '{manifestPath}' is empty.";
                    return false;
                }

                return TryParseBindings(json, bindings, out failureReason);
            }
            catch (Exception exception)
            {
                failureReason = $"Unable to read tutorial instrumentation manifest: {exception.Message}";
                bindings.Clear();

                return false;
            }
        }

        #endregion

        #region Manifest Path

        /// <summary>
        /// Find the generated manifest from the Unity project root
        /// </summary>
        private static bool TryFindManifestPath(ICompiledAssembly compiledAssembly, out string manifestPath)
        {
            manifestPath = string.Empty;

            string currentDirectory = Directory.GetCurrentDirectory();

            if (TryFindManifestFromDirectory(currentDirectory, out manifestPath))
            {
                return true;
            }

            if (compiledAssembly?.References == null)
            {
                return false;
            }

            foreach (string reference in compiledAssembly.References)
            {
                string directory = Path.GetDirectoryName(reference);

                if (TryFindManifestFromDirectory(directory, out manifestPath))
                {
                    return true;
                }
            }

            return false;
        }

        /// <summary>
        /// Walk through parent directories until the Unity project manifest is found
        /// </summary>
        private static bool TryFindManifestFromDirectory(string directoryPath, out string manifestPath)
        {
            manifestPath = string.Empty;

            if (string.IsNullOrWhiteSpace(directoryPath))
            {
                return false;
            }

            DirectoryInfo directory = new DirectoryInfo(directoryPath);

            while (directory != null)
            {
                string candidatePath = Path.Combine(directory.FullName, ManifestRelativePath);

                if (File.Exists(candidatePath))
                {
                    manifestPath = candidatePath;
                    return true;
                }

                directory = directory.Parent;
            }

            return false;
        }

        #endregion

        #region Parsing

        /// <summary>
        /// Parse every binding object contained inside the generated JSON
        /// </summary>
        private static bool TryParseBindings(string json, List<TutorialInstrumentationBinding> bindings, out string failureReason)
        {
            failureReason = string.Empty;

            MatchCollection objectMatches = Regex.Matches(
                json,
                @"\{[^{}]*\}",
                RegexOptions.Singleline
            );

            HashSet<string> registeredBindings = new HashSet<string>(StringComparer.Ordinal);

            foreach (Match objectMatch in objectMatches)
            {
                string objectJson = objectMatch.Value;

                if (!TryReadStringProperty(objectJson, "scriptName", out string scriptName))
                {
                    continue;
                }

                if (!TryReadStringProperty(objectJson, "methodName", out string methodName) || !TryReadStringProperty(objectJson, "stepGuid", out string stepGuid) || !TryReadStringProperty(objectJson, "graphGuid", out string graphGuid))
                {
                    failureReason = "The tutorial instrumentation manifest contains an incomplete binding.";
                    bindings.Clear();

                    return false;
                }

                scriptName = scriptName.Trim();
                methodName = methodName.Trim();
                stepGuid = stepGuid.Trim();
                graphGuid = graphGuid.Trim();

                if (string.IsNullOrWhiteSpace(scriptName) || string.IsNullOrWhiteSpace(methodName) || string.IsNullOrWhiteSpace(stepGuid))
                {
                    failureReason = "The tutorial instrumentation manifest contains an invalid empty binding value.";
                    bindings.Clear();

                    return false;
                }

                /*
                 * GraphGuid is intentionally excluded from this key.
                 * If the same Step/method appears in several graphs, the same
                 * notification must only be injected once.
                 */
                string bindingKey = $"{scriptName}|{methodName}|{stepGuid}";

                if (!registeredBindings.Add(bindingKey))
                {
                    continue;
                }

                bindings.Add(
                    new TutorialInstrumentationBinding(
                        graphGuid,
                        scriptName,
                        methodName,
                        stepGuid
                    )
                );
            }

            return true;
        }

        /// <summary>
        /// Read one string property from a generated JSON object
        /// </summary>
        private static bool TryReadStringProperty(string jsonObject, string propertyName, out string value)
        {
            value = string.Empty;

            Match match = Regex.Match(jsonObject, $"\"{Regex.Escape(propertyName)}\"\\s*:\\s*\"(?<value>[^\"]*)\"", RegexOptions.Singleline);

            if (!match.Success)
            {
                return false;
            }

            value = match.Groups["value"].Value;
            return true;
        }

        #endregion
    }
}